name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  format_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup tools
        uses: jdx/mise-action@v2

      - name: Run gofmt
        run: gofmt -w .

      - name: Check uncommitted changes
        run: git diff --exit-code

      - if: failure()
        run: echo "::error::Check failed, please run 'make format' and commit the changes."

  format_kotlin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup tools
        uses: jdx/mise-action@v2

      - name: Run ktfmt check
        run: ./gradlew ktfmtCheck
        working-directory: plugin

      - if: failure()
        run: echo "::error::Check failed, please run 'make format' and commit the changes."

  protobuf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup tools
        uses: jdx/mise-action@v2

      - name: Compile protobufs
        run: make proto

      - name: Check uncommitted changes
        run: git diff --exit-code

      - if: failure()
        run: echo "::error::Check failed, please run 'make proto' and commit the changes."
