name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Create gradle.properties
        run: |
          cat <<EOF >> $HOME/.gradle/gradle.properties
          github_actor=${{ secrets.GRADLE_GITHUB_ACTOR }}
          github_token=${{ secrets.GRADLE_GITHUB_TOKEN }}
          EOF

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: 2.x
          args: release --clean --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
